# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: practical-dapr
extensions:
- name: dapr
# registry: dapracr.azurecr.io docker.pkg.github.com/thangchung/practical-dapr
registry: vndg
services:
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2017-latest
  env:
    - name: SA_PASSWORD
      value: "P@ssw0rd"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
# - name: redis
#   image: redis
#   bindings:
#     - port: 6973
- name: graph-api
  project: src/GraphApi/CoolStore.GraphApi/CoolStore.GraphApi.csproj
- name: identity-api
  project: src/Identity/CoolStore.IdentityServer/CoolStore.IdentityServer.csproj
- name: product-catalog-api
  project: src/ProductCatalog/CoolStore.ProductCatalogApi/CoolStore.ProductCatalogApi.csproj
- name: inventory-api
  project: src/Inventory/CoolStore.InventoryApi/CoolStore.InventoryApi.csproj
- name: webui
  project: src/WebUI/CoolStore.WebUI.Host/CoolStore.WebUI.Host.csproj
