# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: practical-dapr

extensions:
- name: dapr
  log-level: debug
  config: appconfig
# - name: zipkin
# - name: elastic
#   logPath: ./.logs

# registry: dapracr.azurecr.io or docker.pkg.github.com/thangchung/practical-dapr
registry: vndg

services:

- name: graphapi
  project: src/GraphApi/CoolStore.GraphApi/CoolStore.GraphApi.csproj
- name: identityserver
  project: src/Identity/CoolStore.IdentityServer/CoolStore.IdentityServer.csproj
- name: productcatalogapi
  project: src/ProductCatalog/CoolStore.ProductCatalogApi/CoolStore.ProductCatalogApi.csproj
- name: inventoryapi
  project: src/Inventory/CoolStore.InventoryApi/CoolStore.InventoryApi.csproj
- name: webuihost
  project: src/WebUI/CoolStore.WebUI.Host/CoolStore.WebUI.Host.csproj

- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2017-latest
  env:
    - name: SA_PASSWORD
      value: "P@ssw0rd"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
      connectionString: Data Source=${host},${port};Initial Catalog=coolstoredb;User Id=sa;Password=${env:SA_PASSWORD};MultipleActiveResultSets=True;
- name: redis
  image: redis
  bindings:
    - port: 6379
