# Default values for zipkin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openzipkin/zipkin
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9411

resources:
  requests:
    cpu: 200m
    memory: 100Mi
  limits:
    cpu: 300m
    memory: 150Mi

nodeSelector: {}

tolerations: []

affinity: {}
