name: graphql-ci

on:
  push:
    branches:
      - master
      - feature/*
    paths:
      - "src/GraphApi/**"
      - "src/BuildingBlocks/**"
      - ".github/workflows/graph-api.yml"
  pull_request:
    branches: [ master ]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.3.20216.6

    - name: Build with dotnet
      run: dotnet build src/GraphApi/CoolStore.GraphApi/CoolStore.GraphApi.csproj --configuration Release

  # build-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: aarnott/nbgv@v0.3
  #     with:
  #       setAllVars: true
  #   - name: Build docker image
  #     run: docker build . --file ./src/GraphApi/CoolStore.GraphApi/Dockerfile --tag image
  #   - name: Log into registry
  #     run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
  #   - name: Push image
  #     run: |
  #       VERSION=$NBGV_SemVer2
  #       IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/dapr-graph-api
  #       docker tag image $IMAGE_ID:$VERSION
  #       docker push $IMAGE_ID:$VERSION
