name: identity-ci

on:
  push:
    branches: [ master ]
    paths:
      - "src/Identity/**"
      - "src/BuildingBlocks/**"
      - ".github/workflows/identity-api.yml"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.event.path }}
    - run: |
          git fetch --unshallow

    # - uses: aarnott/nbgv@v0.3
    #   with:
    #     setAllVars: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.3.20216.6

    - name: Build with dotnet
      run: dotnet build src/Identity/CoolStore.IdentityServer/CoolStore.IdentityServer.csproj --configuration Release
