fullnameOverride: sqlserver
image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2017-latest
acceptEula:
  value: "Y"
edition:
  value: "Developer"
persistence:
  enabled: false
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 1Gi
sapassword: "P@ssw0rd"